language: bash

git:
  quiet: true
  submodules: false

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11

env:
  global:
    - BACKUP="$HOME/.rm_backup"
    - RUN="/bin/bash $HOME/.rm_backup/script/rm_alias.sh"

before_install: 
  - git clone https://github.com/AaronV77/rm_backup.git
  - ./setup.sh --test
  - cd testing

script:
  - sh test_1_bash.sh || travis_terminate 1;
  - bash test_2_backup_dir.sh || travis_terminate 1;
  - bash test_3_file_removal.sh || travis_terminate 1;
  - bash test_4_empty_folder_removal.sh || travis_terminate 1;
  - bash test_5_not_empty_folder_removal.sh || travis_terminate 1;
  - bash test_6_non-existent_item.sh || travis_terminate 1;
  - bash test_7_multiple_file_removal.sh || travis_terminate 1;
  - bash test_8_multiple_empty_folder_removal.sh || travis_terminate 1;
  - bash test_9_multiple_not_empty_folder_removal.sh || travis_terminate 1;
  - bash test_10_duplicate_file_removal.sh || travis_terminate 1;
  - bash test_11_duplicate_empty_folder_removal.sh || travis_terminate 1;
  - bash test_12_duplicate_not_empty_folder_removal.sh || travis_terminate 1;
  - bash test_13_persistance_period.sh || travis_terminate 1;
  - bash test_14_star_folder_removal.sh || travis_terminate 1;
  - bash test_15_filename_star_removal.sh || travis_terminate 1;
  - bash test_16_cleanup.sh || travis_terminate 1;